services:
  spring_boot_docker_compose_1:
    image: spring-boot-docker-compose
    container_name: spring_boot_docker_compose_1
    ports:
      - 8080:8080

  dockerize-vuejs-app-1:
    image: dockerize-vuejs-app
    container_name: dockerize-vuejs-app-1
    ports:
      - 7080:7080
