services:
  spring_boot_docker_compose_1:
    image: spring-boot-docker-compose
    container_name: spring_boot_docker_compose_1
    ports:
      - 8081:8080
    networks:
      - huongdanjava

  spring_boot_docker_compose_2:
    image: spring-boot-docker-compose
    container_name: spring_boot_docker_compose_2
    ports:
      - 8082:8080
    networks:
      - huongdanjava

  nginx:
    image: nginx:0.0.1
    ports:
      - 80:80

networks:
  huongdanjava:
    driver: bridge
